---
- name: "Playbook to show censoring"
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create a new token using username/password
      ansible.controller.token:
        description: Temp token
        scope: write
        state: present
        controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
        controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
        controller_host: '{{ lookup("env", "CONTROLLER_HOST") }}'
        validate_certs: False
    
    - name: Create team
      ansible.controller.team:
        name: Number 1
        description: Team Description
        organization: Default
        state: present
        controller_oauthtoken: '{{ lookup("env", "CONTROLLER_OAUTH_TOKEN") }}'
        controller_host: '{{ lookup("env", "CONTROLLER_HOST") }}'
        validate_certs: false
    
    - name: Call Automation Controller API
      when: ansible_facts['controller_token'] is defined and
            ansible_facts['controller_token']['token'] is defined
      block:
        - name: List running jobs
          register: testing_jobs
          ignore_errors: true
          environment:
            CONTROLLER_OAUTH_TOKEN: "{{ ansible_facts['controller_token']['token'] }}"
          ansible.controller.job_list:
            status: successful
            query:
              playbook: "12345678.yml"
            #aap_token: "{{ ansible_facts['aap_token']['token'] }}"
            controller_host: '{{ lookup("env", "CONTROLLER_HOST") }}'
            validate_certs: false

        - name: Debug token
          ansible.builtin.debug:
            var: ansible_facts['controller_token']
            verbosity: 3

    - name: test debug
      no_log: True
      ansible.builtin.debug:
        msg: "2024-05-15"
        verbosity: 3

