---
- name: "Playbook to show censoring"
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: test debug
      no_log: True
      ansible.builtin.debug:
        msg: "2024-05-15"
        verbosity: 3

